### DISCUSSION TITLE
No files or folders found in mounted directory

### DISCUSSION THREAD

**Discussion by GrimmReaperNL** [jlesage/docker-jmkvpropedit#3] [Q&A] [answered]
Hello,

I'm running JMKVPropEdit in a docker container through dockge on truenas. My compose file is the following:
```
version: "3"
services:
  jmkvpropedit:
    image: jlesage/jmkvpropedit
    ports:
      - 5800:5800
    volumes:
      - /mnt/TrueNAS/apps/jmkvpropedit:/config:rw
      - /mnt/TrueNAS/storage/media:/storage:rw
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/Amsterdam
      - DARK_MODE=1
networks: {}
```
The storage location should show a couple of folders, and for testing I've put in at least one file.
But when I'm trying to add files or folders, the 'storage' location is empty.

Could someone tell me what I'm doing wrong? Thank you.
